name: shwapno_survey
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg_provider: ^1.0.7
  fluttertoast: ^8.2.12
  pin_code_fields: ^8.0.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Poppins-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

